"""Generates docs/device_matrix.md FROM docs/benchmark_results.json --
real numbers produced by scripts/run_benchmark.py, never hand-typed. Run
run_benchmark.py first (or after any pipeline change) to refresh the
source data this reads.
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_PATH = REPO_ROOT / "docs" / "benchmark_results.json"
OUT_PATH = REPO_ROOT / "docs" / "device_matrix.md"


def _format_accuracy(result: dict) -> str:
    status = "PASS" if result["passed"] else "FAIL"
    return f"{result['gate_name']}: {status} ({result['metric_description']} = {result['actual_value']:.3f}, threshold {result['threshold']:.3f})"


def main() -> None:
    if not RESULTS_PATH.exists():
        raise SystemExit(f"{RESULTS_PATH} not found -- run scripts/run_benchmark.py first")

    results = json.loads(RESULTS_PATH.read_text())

    by_tier: dict[str, list[dict]] = defaultdict(list)
    for r in results:
        by_tier[r["tier"]].append(r)

    lines = [
        "# Device Matrix (Part 1 deliverable)",
        "",
        "Generated by `scripts/generate_device_matrix.py` directly from "
        "`docs/benchmark_results.json` (produced by `scripts/run_benchmark.py` "
        "against the real benchmark set) -- every number below is a real "
        "measured result, not a manual claim.",
        "",
        "| Tier | Device Tested | Accuracy Achieved (per gate) | Notes |",
        "|---|---|---|---|",
    ]

    for tier in ("lidar", "video", "photo"):
        tier_results = by_tier.get(tier, [])
        if not tier_results:
            lines.append(f"| {tier} | -- | no benchmark data yet | not run |")
            continue

        device = tier_results[0]["device"]
        accuracy_lines = "<br>".join(_format_accuracy(r) for r in tier_results)
        caveats = [r["detail"] for r in tier_results if "[CAVEAT" in r["detail"]]
        notes = "<br>".join(c.split("[CAVEAT: ")[1].rstrip("]") for c in caveats) if caveats else "--"

        lines.append(f"| {tier} | {device} | {accuracy_lines} | {notes} |")

    room_ids = sorted({r["room_id"] for r in results})
    lines.append("")
    lines.append(
        f"Only `{'`, `'.join(room_ids)}` (the room(s) with rectangular ground truth) "
        "is represented here -- see `docs/benchmark_report.md` for why any other "
        "real rooms aren't auto-scored."
    )

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Written to {OUT_PATH}")


if __name__ == "__main__":
    main()
