"""Builds the real Part 3 head-to-head comparison: our LiDAR-tier output vs.
magicplan vs. ground truth, on bedroom_1 and common-space.

Shared dimensions only: a dimension is compared only when both our output
and the competitor's parsed export have a value for it. Only bedroom_1
qualifies -- common-space's ground truth is an irregular room (see
media/ground_truth/common-space/ground_truth.json) with no single L x B /
single-ceiling-height representation to compare magicplan's box-shaped
measurement against, so it's excluded here rather than force-matched.
"""
from __future__ import annotations

import json
from pathlib import Path

from pipeline.adapters.lidar_adapter import LidarAdapter
from pipeline.competitor_parser import load_competitor_measurements
from pipeline.head_to_head import HeadToHeadReport, build_report
from pipeline.room_reconstruction import reconstruct_room

REPO_ROOT = Path(__file__).resolve().parent.parent

COMPETITOR_APP = "magicplan"
COMPETITOR_VERSION = "2026.34.1"
ROOMS_TESTED = ["bedroom_1", "common-space"]
ROOMS_SCORED = ["bedroom_1"]
EXCLUDED_ROOM_NOTE = (
    "common-space was captured with both our pipeline and magicplan, but is excluded from "
    "scoring: its ground truth is an irregular room (see "
    "media/ground_truth/common-space/ground_truth.json -- a per-wall perimeter, not a single "
    "L x B box), so there is no single width/length/ceiling-height ground-truth value to "
    "compare magicplan's box-shaped measurement against without inventing a mapping."
)


def _sorted_walls_cm(room) -> list[float]:
    return sorted(w.length.value for w in room.walls)


def build_real_head_to_head_report() -> tuple[HeadToHeadReport, dict]:
    """Loads real data and builds the comparison. Returns the report plus
    narrative metadata, so every output document (table CSV/markdown, the
    written-up report) is generated from this one source -- numbers can't
    drift between documents."""
    ground_truth = json.loads((REPO_ROOT / "media/ground_truth/bedroom_1/ground_truth.json").read_text())
    competitor = load_competitor_measurements(REPO_ROOT / "media/competitor_benchmark/magicplan/measurements.json")

    lidar_dir = next((REPO_ROOT / "media/lidar/bedroom_1").iterdir())
    lidar_capture = LidarAdapter().load(lidar_dir, room_id="bedroom_1")
    our_room = reconstruct_room(lidar_capture, room_id="bedroom_1", name="bedroom_1", device="iPhone17,1")

    gt_length = ground_truth["floor_dimensions_cm"]["length"]
    gt_breadth = ground_truth["floor_dimensions_cm"]["breadth"]
    gt_ceiling = ground_truth["ceiling_height_cm"]

    our_walls_sorted = _sorted_walls_cm(our_room)  # [short, short, long, long]
    our_breadth, our_length = our_walls_sorted[0], our_walls_sorted[-1]

    their = competitor["bedroom_1"]
    their_length, their_breadth = their.length.value, their.width.value

    dimensions = [
        ("bedroom_1_length", gt_length, our_length, their_length),
        ("bedroom_1_breadth", gt_breadth, our_breadth, their_breadth),
        ("bedroom_1_ceiling_height", gt_ceiling, our_room.ceiling_height.value, their.ceiling_height.value),
    ]

    report = build_report(dimensions)
    metadata = {
        "competitor_app": COMPETITOR_APP,
        "competitor_version": COMPETITOR_VERSION,
        "rooms_tested": ROOMS_TESTED,
        "rooms_scored": ROOMS_SCORED,
        "excluded_room_note": EXCLUDED_ROOM_NOTE,
        "device": "iPhone17,1",
    }
    return report, metadata


def main() -> None:
    report, metadata = build_real_head_to_head_report()

    print(report.to_markdown())

    csv_path = REPO_ROOT / "docs" / "head_to_head_table.csv"
    csv_path.write_text(report.to_csv())

    md_path = REPO_ROOT / "docs" / "head_to_head_table.md"
    md_path.write_text(
        f"# Head-to-Head: Our Pipeline vs. {metadata['competitor_app']} ({metadata['competitor_version']})\n\n"
        "LiDAR tier, bedroom_1 (the only benchmark room with ground truth in a shape "
        "comparable to both our box-room reconstruction and magicplan's box-room output -- "
        "see docs/head_to_head.md for why common-space is excluded).\n\n"
        + report.to_markdown()
        + "\n"
    )

    report_path = REPO_ROOT / "docs" / "head_to_head_report.md"
    report_path.write_text(_render_report_md(report, metadata))

    print(f"\nWritten to {csv_path}")
    print(f"Written to {md_path}")
    print(f"Written to {report_path}")


def _render_report_md(report: HeadToHeadReport, metadata: dict) -> str:
    pass_fail = "PASS" if report.win_or_tie_fraction >= 0.70 else "FAIL"
    return (
        "# Part 3: Head-to-Head Report\n\n"
        "Generated by `scripts/run_head_to_head.py` from real data -- every number below "
        "comes directly from `pipeline.head_to_head.HeadToHeadReport`, not retyped by hand.\n\n"
        f"**Competitor app:** {metadata['competitor_app']}, version {metadata['competitor_version']} (free tier)\n\n"
        f"**Device:** {metadata['device']}\n\n"
        f"**Rooms tested:** {', '.join(metadata['rooms_tested'])}\n\n"
        f"**Rooms scored:** {', '.join(metadata['rooms_scored'])}\n\n"
        f"{metadata['excluded_room_note']}\n\n"
        "## Comparison table\n\n"
        f"{report.to_markdown()}\n\n"
        "## Result\n\n"
        f"**{pass_fail}** -- {report.win_or_tie_fraction * 100:.1f}% beat-or-tie rate against the "
        "assessment's >=70% bar. "
        + (
            "This traces directly to the two known LiDAR reconstruction issues on record "
            "(box-footprint fit, ceiling-height percentile trim) -- see docs/benchmark_report.md "
            "and CLAUDE.md -- and is independent evidence for prioritizing them in the Part 4 fix loop."
            if pass_fail == "FAIL"
            else "Our pipeline meets or beats the competitor on the required fraction of shared dimensions."
        )
    )


if __name__ == "__main__":
    main()
